/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View.ViewQL;

import Service.impl.BanServiceImpl;
import Service.impl.HoaDonChiTietServiceIblm;
import Service.impl.HoaDonServiceIblm;
import Service.impl.SanPhamServiceImpl;
import Service.impl.ToppingServiceImpl;
import ViewModels.Ban;
import ViewModels.HoaDon;
import ViewModels.HoaDonChiTiet;
import ViewModels.NhanVienViewModel;
import ViewModels.SanPham;
import ViewModels.Topping;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Admin
 */
public class ViewHoaDon extends javax.swing.JInternalFrame {

    private DefaultTableModel dtmHoaDon = new DefaultTableModel();
    private DefaultTableModel dtm = new DefaultTableModel();
    private HoaDonServiceIblm iplmHD = new HoaDonServiceIblm();
    private List<HoaDon> listHD = new ArrayList<>();
    private DefaultComboBoxModel box1 = new DefaultComboBoxModel();
    private List<Ban> listB = new ArrayList<>();
    private List<SanPham> listSP = new ArrayList<>();
    private List<HoaDonChiTiet> listHDCT = new ArrayList<>();
    private List<Topping> listTP = new ArrayList<>();
    private List<NhanVienViewModel> listNV = new ArrayList<>();
    private Service.impl.BanServiceImpl iplmB = new BanServiceImpl();
    private Service.impl.SanPhamServiceImpl iplmSP = new SanPhamServiceImpl();
    private Service.impl.HoaDonChiTietServiceIblm iplmHDCT = new HoaDonChiTietServiceIblm();
    private Service.impl.ToppingServiceImpl iplmTP = new ToppingServiceImpl();

    /**
     * Creates new form Menu2
     */
    public ViewHoaDon() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI uI = (BasicInternalFrameUI) this.getUI();
        uI.setNorthPane(null);
        String header[] = {"Mã Hóa Đơn", "Tên Bàn", "Tên Nhân Viên", "Ngày Lập Hoá Đơn", "Phương Thức Thanh Toán", "Tên Sản Phẩm", "Giá Bán", "Số Lượng", "Tên Topping", "Thành Tiền", "Tình Trạng"};
        bangHDCT.setModel(dtm);
        dtm.setColumnIdentifiers(header);
        listHD = iplmHD.getAll();
        cbbSearchTT.setModel(box1);
        box1.addElement("All");
        box1.addElement("Đã thanh toán");
        box1.addElement("Huỷ");
        String[] headersHD = {"Mã HD", "Ngày lập", "Nhân viên", "Trạng thái"};
        bangHD.setModel(dtmHoaDon);
        dtmHoaDon.setColumnIdentifiers(headersHD);
        listHD = iplmHD.getAllViewHD();
        showDataHD(listHD);
    }

    private void showDataHD(List<HoaDon> list) {
        dtmHoaDon.setRowCount(0);
        for (HoaDon x : list) {
            dtmHoaDon.addRow(new Object[]{x.getMaHD(), x.getNgayLapHD(), x.getTenNV().getTenNV(), x.getTinhTrang()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtSearchMaHD = new javax.swing.JTextField();
        cbbSearchTT = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNgaybatDau = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        bltXuatBillPDF = new javax.swing.JButton();
        txtNgayCuoi = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        txtMa = new javax.swing.JLabel();
        txtBan = new javax.swing.JLabel();
        txtNhanVien = new javax.swing.JLabel();
        txtNgay = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JLabel();
        txtPttt = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPrintBill = new javax.swing.JTextArea();
        bltSearch = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangHD = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        bltXuatHD = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        bangHDCT = new javax.swing.JTable();
        txtFake = new javax.swing.JLabel();
        txtTTFAKE = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(871, 699));

        jInternalFrame1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        txtSearchMaHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchMaHDKeyReleased(evt);
            }
        });

        cbbSearchTT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbSearchTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbSearchTTActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã Hóa Đơn:");

        jLabel3.setText("Trạng Thái:");

        jLabel5.setText("Thời gian cuối: ");

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bltXuatBillPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon-bill-new.png"))); // NOI18N
        bltXuatBillPDF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bltXuatBillPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bltXuatBillPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bltXuatBillPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bltXuatBillPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtMa.setText("jLabel6");

        txtBan.setText("jLabel6");

        txtNhanVien.setText("jLabel6");

        txtNgay.setText("jLabel6");

        txtTongTien.setText("jLabel6");

        txtPttt.setText("jLabel6");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtMa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTongTien))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtBan)
                        .addGap(18, 18, 18)
                        .addComponent(txtPttt))
                    .addComponent(txtNhanVien)
                    .addComponent(txtNgay)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMa)
                    .addComponent(txtTongTien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBan)
                    .addComponent(txtPttt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNgay))
        );

        txtPrintBill.setColumns(20);
        txtPrintBill.setRows(5);
        jScrollPane2.setViewportView(txtPrintBill);

        bltSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_icon.jpg"))); // NOI18N
        bltSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bltSearchActionPerformed(evt);
            }
        });

        jLabel6.setText("Thời gian đầu: ");

        jLabel4.setText("to");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearchMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNgaybatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgayCuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bltSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cbbSearchTT, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSearchMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtNgayCuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNgaybatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbbSearchTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(bltSearch, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(255, 0, 51))); // NOI18N

        bangHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bangHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangHDMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bangHD);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Xuất All Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12))); // NOI18N

        bltXuatHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon.jpg"))); // NOI18N
        bltXuatHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bltXuatHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bltXuatHD, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bltXuatHD)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa Đơn Chi Tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 14), new java.awt.Color(255, 0, 51))); // NOI18N

        bangHDCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bangHDCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangHDCTMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(bangHDCT);

        txtFake.setText("jLabel7");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFake, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(467, 467, 467))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(txtFake, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtTTFAKE.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(txtTTFAKE, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTTFAKE, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );

        setBounds(0, 0, 1084, 753);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchMaHDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchMaHDKeyReleased
        if (txtSearchMaHD.getText().equalsIgnoreCase("")) {
            listHD = iplmHD.getAllViewHD();
            showDataHD(listHD);
        } else {
            List<HoaDon> searchTheoMaHD = iplmHD.searchTheoMaHD(txtSearchMaHD.getText());
            showDataHD(searchTheoMaHD);
        }
    }//GEN-LAST:event_txtSearchMaHDKeyReleased

    private void cbbSearchTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSearchTTActionPerformed
        if (cbbSearchTT.getSelectedItem().toString().equalsIgnoreCase("All")) {
            listHD = iplmHD.getAllViewHD();
            showDataHD(listHD);
        } else {
            List<HoaDon> searchTheoTT = iplmHD.searchTheoTT(cbbSearchTT.getSelectedItem().toString());
            showDataHD(searchTheoTT);
        }
    }//GEN-LAST:event_cbbSearchTTActionPerformed

    private void bangHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangHDMouseClicked
        int row = bangHD.getSelectedRow();
        String ma = bangHD.getValueAt(row, 0).toString();
        String tt = bangHD.getValueAt(row, 3).toString();
        HoaDon hd = iplmHD.getOne(ma);
        listHD = iplmHD.getAllHD(ma);
        showData(listHD);
        int row2 = bangHDCT.getSelectedRow();
        txtFake.setText("check");
        fillData(row2);
        txtTTFAKE.setText(tt);
    }//GEN-LAST:event_bangHDMouseClicked

    private void bltXuatHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bltXuatHDActionPerformed
        InhoaDon();
    }//GEN-LAST:event_bltXuatHDActionPerformed

    private void bltXuatBillPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bltXuatBillPDFActionPerformed
        if (txtFake.getText().equalsIgnoreCase("check")) {
            if (txtTTFAKE.getText().equalsIgnoreCase("Đã thanh toán")) {
                txtPrintBill.append("\t\tHÓA ĐƠN THANH TOÁN \n\n"
                        + "\t\t   Mã Hóa Đơn:  " + txtMa.getText() + "\n"
                        + "+++--------------------------------------------------------------------------------------------------------+++\n"
                        + "\tBàn:\t\t\t" + txtBan.getText() + "\n"
                        + "\tNhân Viên:\t\t\t" + txtNhanVien.getText() + "\n"
                        + "\tNgày:\t\t\t" + txtNgay.getText() + "\n"
                        + "\tPhương thức thanh toán:\t\t" + txtPttt.getText() + "\n\n"
                        + "\tTên Mặt Hàng:  " + "  Đơn Giá:   " + "\tSố Lượng:   " + "\tTopping:   "
                        + "\n_______________________________________________________________________________________________________________\n"
                );
                DefaultTableModel modelHDCT = new DefaultTableModel();
                modelHDCT = (DefaultTableModel) bangHDCT.getModel();
                for (int i = 0; i < modelHDCT.getRowCount(); i++) {
                    String maHD = modelHDCT.getValueAt(i, 0).toString();
                    String tenB = modelHDCT.getValueAt(i, 1).toString();
                    String tenNV = modelHDCT.getValueAt(i, 2).toString();
                    String ngayLap = modelHDCT.getValueAt(i, 3).toString();
                    String pttt = modelHDCT.getValueAt(i, 4).toString();
                    String tenSP = modelHDCT.getValueAt(i, 5).toString();
                    String donG = modelHDCT.getValueAt(i, 6).toString();
                    String soL = modelHDCT.getValueAt(i, 7).toString();
                    String tenTP = modelHDCT.getValueAt(i, 8).toString();
                    String tienT = modelHDCT.getValueAt(i, 9).toString();
                    String status = modelHDCT.getValueAt(i, 10).toString();
                    txtPrintBill.setText(txtPrintBill.getText() + "\t" + tenSP + "\t   " + donG + "\t" + soL + "\t" + tenTP + "\n");
                }
                txtPrintBill.setText(txtPrintBill.getText()
                        + "================================================================================\n\n"
                        + "\tTổng tiền:\t\t" + txtTongTien.getText() + " " + "VND" + "\n\n\n\n\n"
                        + "           +++++++=====CHÚC QUÝ KHÁCH 1 NGÀY TỐT LÀNH !=====+++++++");

                try {
                    txtPrintBill.print();
                    JOptionPane.showMessageDialog(this, "In thành công !");
                } catch (PrinterException ex) {
                    Logger.getLogger(ViewHoaDon.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "In thất bại !");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không được in hóa đơn hủy !");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chưa chọn hóa đơn !");
        }
    }//GEN-LAST:event_bltXuatBillPDFActionPerformed

    private void bangHDCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangHDCTMouseClicked
        int row = bangHDCT.getSelectedRow();
        txtFake.setText("check");
        fillData(row);
    }//GEN-LAST:event_bangHDCTMouseClicked

    private void bltSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bltSearchActionPerformed
        try {
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String date1 = df.format(txtNgaybatDau.getDate());
            String date2 = df.format(txtNgayCuoi.getDate());
            List<HoaDon> searchTheoDate = iplmHD.searchTheoDate(date1, date2);
            showDataHD(searchTheoDate);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Tìm kiếm thất bại !");
        }
    }//GEN-LAST:event_bltSearchActionPerformed
    private void fillData(int index) {
        double tong = 0;
        for (int i = 0; i < bangHDCT.getRowCount(); i++) {
            String maHD = bangHDCT.getValueAt(i, 0).toString();
            String tenB = bangHDCT.getValueAt(i, 1).toString();
            String tenNV = bangHDCT.getValueAt(i, 2).toString();
            String ngayLap = bangHDCT.getValueAt(i, 3).toString();
            String pttt = bangHDCT.getValueAt(i, 4).toString();
            Double tien = Double.valueOf(bangHDCT.getValueAt(i, 9).toString());
            tong += tien;
            txtMa.setText(maHD);
            txtBan.setText(tenB);
            txtNgay.setText(ngayLap);
            txtNhanVien.setText(tenNV);
            txtPttt.setText(pttt);
//            txtTongTien.setText();
        }
//        String giamG = bangHDCT.getValueAt(index, 10).toString();
        double tongTien = tong;
        txtTongTien.setText(String.valueOf(tongTien));

//        HoaDonChiTiet hdct = listHDCT.get(index);
//        HoaDon hd = listHD.get(index);
//        Ban b = listB.get(index);
//        NhanVienViewModel nv = listNV.get(index);
    }

    private void showData(List<HoaDon> list) {
        dtm.setRowCount(0);
        for (HoaDon x : list) {
            dtm.addRow(x.toRowData());
        }
    }

    public void InhoaDon() {
        try {
            XSSFWorkbook workbook = new XSSFWorkbook();
            XSSFSheet spreadSheet = workbook.createSheet("Hóa Đơn");

            XSSFRow row = null;
            Cell cell = null;
            row = spreadSheet.createRow((short) 2);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);

            cell.setCellValue("DANH SÁCH HÓA ĐƠN");

            row = spreadSheet.createRow((short) 3);
            row.setHeight((short) 500);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("MÃ HÓA ĐƠN");
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("TÊN BÀN");
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("TÊN NHÂN VIÊN");
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("NGÀY LẬP HÓA ĐƠN");
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("PHƯƠNG THỨC THANH TOÁN");
            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("TÊN SẢN PHẨM");
            cell = row.createCell(6, CellType.STRING);
            cell.setCellValue("GIÁ BÁN");
            cell = row.createCell(7, CellType.STRING);
            cell.setCellValue("SỐ LƯỢNG");
            cell = row.createCell(8, CellType.STRING);
            cell.setCellValue("TOPPING");
            cell = row.createCell(9, CellType.STRING);
            cell.setCellValue("TRẠNG THÁI");
            List<HoaDon> listHD = iplmHD.getAll();

            for (int i = 0; i < listHD.size(); i++) {
                HoaDon hd = listHD.get(i);
//                Ban b = listB.get(i);
//                SanPham sp = listSP.get(i);
//                HoaDonChiTiet hdct = listHDCT.get(i);
//                Topping tp = listTP.get(i);
                row = spreadSheet.createRow((short) 4 + i);
                row.setHeight((short) 400);
                row.createCell(0).setCellValue(hd.getMaHD());
                row.createCell(1).setCellValue(hd.getBan().getTenBan());
                row.createCell(2).setCellValue("Nhân Viên A");
                row.createCell(3).setCellValue(hd.getNgayLapHD());
                row.createCell(4).setCellValue("Tiền mặt");
                row.createCell(5).setCellValue(hd.getSp().getTenSP());
                row.createCell(6).setCellValue(hd.getSp().getGiaBan());
                row.createCell(7).setCellValue(hd.getHdct().getSoLuong());
                row.createCell(8).setCellValue(hd.getTp().getTopping());
                row.createCell(9).setCellValue(hd.getTinhTrang());
            }
            FileOutputStream out = new FileOutputStream(new File("D:\\hdct.xlsx"));
            workbook.write(out);
            out.close();
            JOptionPane.showMessageDialog(this, "Xuất Hóa Đơn Excel Thành Công !");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangHD;
    private javax.swing.JTable bangHDCT;
    private javax.swing.JButton bltSearch;
    private javax.swing.JButton bltXuatBillPDF;
    private javax.swing.JButton bltXuatHD;
    private javax.swing.JComboBox<String> cbbSearchTT;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel txtBan;
    private javax.swing.JLabel txtFake;
    private javax.swing.JLabel txtMa;
    private javax.swing.JLabel txtNgay;
    private com.toedter.calendar.JDateChooser txtNgayCuoi;
    private com.toedter.calendar.JDateChooser txtNgaybatDau;
    private javax.swing.JLabel txtNhanVien;
    private javax.swing.JTextArea txtPrintBill;
    private javax.swing.JLabel txtPttt;
    private javax.swing.JTextField txtSearchMaHD;
    private javax.swing.JLabel txtTTFAKE;
    private javax.swing.JLabel txtTongTien;
    // End of variables declaration//GEN-END:variables
}
